// ============================================================
// FOODWISE — Master Mock Data (Demo/Development)
// ============================================================
import {
  UserRole,
  UrgencyLevel,
  FoodStatus,
  OrderStatus,
  RescueRequestStatus,
  FoodCategory,
} from '@/types';

function getDeadline(hoursFromNow) {
  const d = new Date();
  d.setHours(d.getHours() + hoursFromNow);
  return d.toISOString();
}

function getPreparedAt(hoursAgo) {
  const d = new Date();
  d.setHours(d.getHours() - hoursAgo);
  return d.toISOString();
}

// ============================================================
// PROVIDERS
// ============================================================
export const mockProviders = [
  {
    id: 'prov-1',
    user_id: 'u1',
    userId: 'u1',
    name: 'Taj Coromandel',
    business_name: 'Taj Coromandel',
    businessType: 'HOTEL',
    business_type: 'HOTEL',
    verification_status: 'VERIFIED',
    isVerified: true,
    address: '37, Mahatma Gandhi Rd, Nungambakkam, Chennai',
    latitude: 13.0617,
    longitude: 80.2458,
    lat: 13.0617,
    lng: 80.2458,
    phone: '+91 44 6600 2827',
    description: 'Luxury heritage hotel featuring fine dining, banquets, and authentic Indian & international kitchens.',
    rating: 4.8,
    total_reviews: 412,
    mealsRescuedCount: 680,
    fssaiLicense: '10014042000812',
    created_at: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prov-2',
    user_id: 'u2',
    userId: 'u2',
    name: 'Anjappar Chettinad Restaurant',
    business_name: 'Anjappar Chettinad Restaurant',
    businessType: 'RESTAURANT',
    business_type: 'RESTAURANT',
    verification_status: 'VERIFIED',
    isVerified: true,
    address: '77, Usman Rd, T. Nagar, Chennai',
    latitude: 13.0418,
    longitude: 80.2341,
    lat: 13.0418,
    lng: 80.2341,
    phone: '+91 44 2432 1111',
    description: 'World-famous Chettinad cuisine pioneer serving aromatic biryanis, gravies, and coastal specialties.',
    rating: 4.4,
    total_reviews: 290,
    mealsRescuedCount: 520,
    fssaiLicense: '10017042001554',
    created_at: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prov-3',
    user_id: 'u3',
    userId: 'u3',
    name: 'The French Loaf',
    business_name: 'The French Loaf',
    businessType: 'BAKERY',
    business_type: 'BAKERY',
    verification_status: 'VERIFIED',
    isVerified: true,
    address: '12, Gandhi Nagar 1st Main Rd, Adyar, Chennai',
    latitude: 13.0067,
    longitude: 80.2570,
    lat: 13.0067,
    lng: 80.2570,
    phone: '+91 44 4211 4455',
    description: 'Artisanal French bakery crafting fresh sourdoughs, baguettes, croissants, and dessert pastries daily.',
    rating: 4.6,
    total_reviews: 345,
    mealsRescuedCount: 390,
    fssaiLicense: '10018042001923',
    created_at: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prov-4',
    user_id: 'u4',
    userId: 'u4',
    name: 'Sangeetha Vegetarian Restaurant',
    business_name: 'Sangeetha Vegetarian Restaurant',
    businessType: 'RESTAURANT',
    business_type: 'RESTAURANT',
    verification_status: 'VERIFIED',
    isVerified: true,
    address: '2nd Ave, Anna Nagar, Chennai',
    latitude: 13.0850,
    longitude: 80.2101,
    lat: 13.0850,
    lng: 80.2101,
    phone: '+91 44 2621 3344',
    description: 'Premier pure vegetarian chain loved for traditional South Indian thali meals, dosas, and filter coffee.',
    rating: 4.7,
    total_reviews: 512,
    mealsRescuedCount: 840,
    fssaiLicense: '10015042000998',
    created_at: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prov-5',
    user_id: 'u5',
    userId: 'u5',
    name: 'Nilgiris Supermarket',
    business_name: 'Nilgiris Supermarket',
    businessType: 'SUPERMARKET',
    business_type: 'SUPERMARKET',
    verification_status: 'VERIFIED',
    isVerified: true,
    address: 'Rajiv Gandhi Salai, OMR, Thoraipakkam, Chennai',
    latitude: 12.9348,
    longitude: 80.2312,
    lat: 12.9348,
    lng: 80.2312,
    phone: '+91 44 2496 7788',
    description: 'Leading supermarket dairy & fresh bakery section offering dairy surplus, packaged breads, and fresh greens.',
    rating: 4.3,
    total_reviews: 178,
    mealsRescuedCount: 310,
    fssaiLicense: '10016042001402',
    created_at: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prov-cbe-1',
    user_id: 'u-cbe1',
    userId: 'u-cbe1',
    name: 'Coimbatore Fresh Kitchen',
    business_name: 'Coimbatore Fresh Kitchen',
    businessType: 'RESTAURANT',
    business_type: 'RESTAURANT',
    verification_status: 'VERIFIED',
    isVerified: true,
    address: 'Cross Cut Rd, Gandhipuram, Coimbatore',
    latitude: 11.0168,
    longitude: 76.9558,
    lat: 11.0168,
    lng: 76.9558,
    phone: '+91 422 223 4567',
    description: 'Premier culinary kitchen in Gandhipuram specializing in traditional Kongu Nadu meals and banquet catering.',
    rating: 4.8,
    total_reviews: 320,
    mealsRescuedCount: 420,
    fssaiLicense: '10022042000101',
    created_at: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prov-cbe-2',
    user_id: 'u-cbe2',
    userId: 'u-cbe2',
    name: 'Annapoorna Heritage',
    business_name: 'Annapoorna Heritage',
    businessType: 'RESTAURANT',
    business_type: 'RESTAURANT',
    verification_status: 'VERIFIED',
    isVerified: true,
    address: 'DB Road, RS Puram, Coimbatore',
    latitude: 11.0096,
    longitude: 76.9507,
    lat: 11.0096,
    lng: 76.9507,
    phone: '+91 422 254 0001',
    description: 'Coimbatore legendary pure vegetarian kitchen celebrated for authentic tiffin, ghee roasts, and lunch thalis.',
    rating: 4.9,
    total_reviews: 640,
    mealsRescuedCount: 780,
    fssaiLicense: '10022042000842',
    created_at: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prov-cbe-3',
    user_id: 'u-cbe3',
    userId: 'u-cbe3',
    name: 'Saibaba Artisanal Bakery',
    business_name: 'Saibaba Artisanal Bakery',
    businessType: 'BAKERY',
    business_type: 'BAKERY',
    verification_status: 'VERIFIED',
    isVerified: true,
    address: 'NSR Rd, Saibaba Colony, Coimbatore',
    latitude: 11.0244,
    longitude: 76.9609,
    lat: 11.0244,
    lng: 76.9609,
    phone: '+91 422 244 8899',
    description: 'Fresh local bakery crafting whole wheat breads, tea cakes, and savory veg puffs daily.',
    rating: 4.6,
    total_reviews: 210,
    mealsRescuedCount: 290,
    fssaiLicense: '10022042001150',
    created_at: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// ============================================================
// RESCUE PARTNERS
// ============================================================
export const mockRescuePartners = [
  {
    id: 'ngo-1',
    user_id: 'u-ngo1',
    userId: 'u-ngo1',
    name: 'Robin Hood Army Chennai',
    organization_name: 'Robin Hood Army Chennai',
    organizationType: 'VOLUNTEER_FLEET',
    organization_type: 'VOLUNTEER_FLEET',
    capacity: 250,
    verification_status: 'VERIFIED',
    address: 'Egmore Relief Dispatch Hub, Chennai',
    latitude: 13.0827,
    longitude: 80.2707,
    lat: 13.0827,
    lng: 80.2707,
    phone: '+91 98840 12345',
    beneficiariesServedCount: 8240,
    operating_hours: '12:00 PM - 11:30 PM Daily',
    created_at: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ngo-2',
    user_id: 'u-ngo2',
    userId: 'u-ngo2',
    name: 'No Food Waste Foundation',
    organization_name: 'No Food Waste Foundation',
    organizationType: 'FOOD_BANK',
    organization_type: 'FOOD_BANK',
    capacity: 500,
    verification_status: 'VERIFIED',
    address: 'Mylapore Community Kitchen, Chennai',
    latitude: 13.0368,
    longitude: 80.2676,
    lat: 13.0368,
    lng: 80.2676,
    phone: '+91 90877 90877',
    beneficiariesServedCount: 14600,
    operating_hours: '10:00 AM - 10:00 PM',
    created_at: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ngo-3',
    user_id: 'u-ngo3',
    userId: 'u-ngo3',
    name: 'Annamrita Foundation Chennai',
    organization_name: 'Annamrita Foundation Chennai',
    organizationType: 'MEAL_RELIEF',
    organization_type: 'MEAL_RELIEF',
    capacity: 350,
    verification_status: 'VERIFIED',
    address: 'Guindy Industrial Estate Cluster, Chennai',
    latitude: 13.0067,
    longitude: 80.2000,
    lat: 13.0067,
    lng: 80.2000,
    phone: '+91 44 2250 8899',
    beneficiariesServedCount: 9120,
    operating_hours: '11:00 AM - 9:00 PM',
    created_at: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// ============================================================
// FOOD LISTINGS
// ============================================================
export const mockFoodListings = [
  {
    id: 'fl-1',
    providerId: 'prov-1',
    provider_id: 'prov-1',
    title: 'Royal Biryani & Salan Banquet Platter',
    food_name: 'Royal Biryani & Salan Banquet Platter',
    category: FoodCategory.MEALS,
    description: 'Aromatic Dum Biryani prepared for lunch banquet. Includes rich Mirchi ka Salan and fresh onion raita. Packed in thermal hot-boxes.',
    quantity: 8,
    remaining_quantity: 8,
    unit: 'portions',
    originalPrice: 450,
    original_price: 450,
    discountedPrice: 180,
    surplus_price: 180,
    prepared_at: getPreparedAt(2),
    collection_deadline: getDeadline(1.8),
    expiresAt: getDeadline(1.8),
    location: 'Nungambakkam, Chennai',
    latitude: 13.0617,
    longitude: 80.2458,
    image_url: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',
    images: ['https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800'],
    dietaryTags: ['Non-Veg', 'Halal'],
    dietary_info: ['Non-Veg', 'Halal'],
    status: FoodStatus.ACTIVE,
    urgencyLevel: UrgencyLevel.URGENT,
    urgency_level: UrgencyLevel.URGENT,
    urgencyScore: 0.92,
    isRescueEligible: true,
    provider: mockProviders[0],
    distance: 1.2,
    distanceKm: 1.2,
    recommendationScore: 0.95,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fl-2',
    providerId: 'prov-3',
    provider_id: 'prov-3',
    title: 'Artisan Butter Croissants & Brioche Box',
    food_name: 'Artisan Butter Croissants & Brioche Box',
    category: FoodCategory.BAKERY,
    description: 'Golden flaky French butter croissants and brioche buns baked fresh this morning. Sealed in food-grade kraft pastry boxes.',
    quantity: 12,
    remaining_quantity: 12,
    unit: 'boxes',
    originalPrice: 320,
    original_price: 320,
    discountedPrice: 120,
    surplus_price: 120,
    prepared_at: getPreparedAt(5),
    collection_deadline: getDeadline(3.5),
    expiresAt: getDeadline(3.5),
    location: 'Adyar, Chennai',
    latitude: 13.0067,
    longitude: 80.2570,
    image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800',
    images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800'],
    dietaryTags: ['Veg'],
    dietary_info: ['Veg'],
    status: FoodStatus.ACTIVE,
    urgencyLevel: UrgencyLevel.ATTENTION,
    urgency_level: UrgencyLevel.ATTENTION,
    urgencyScore: 0.65,
    isRescueEligible: true,
    provider: mockProviders[2],
    distance: 2.4,
    distanceKm: 2.4,
    recommendationScore: 0.88,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fl-3',
    providerId: 'prov-4',
    provider_id: 'prov-4',
    title: 'Grand South Indian Thali Feast',
    food_name: 'Grand South Indian Thali Feast',
    category: FoodCategory.MEALS,
    description: 'Traditional lunchtime full meals: Ponni boiled rice, arachuvitta sambar, poondu rasam, kootu, poriyal, appalam, and semiya payasam.',
    quantity: 15,
    remaining_quantity: 15,
    unit: 'thalis',
    originalPrice: 220,
    original_price: 220,
    discountedPrice: 90,
    surplus_price: 90,
    prepared_at: getPreparedAt(3),
    collection_deadline: getDeadline(2.2),
    expiresAt: getDeadline(2.2),
    location: 'Anna Nagar, Chennai',
    latitude: 13.0850,
    longitude: 80.2101,
    image_url: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800',
    images: ['https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800'],
    dietaryTags: ['Veg', 'Pure Vegetarian'],
    dietary_info: ['Veg', 'Pure Vegetarian'],
    status: FoodStatus.ACTIVE,
    urgencyLevel: UrgencyLevel.ATTENTION,
    urgency_level: UrgencyLevel.ATTENTION,
    urgencyScore: 0.72,
    isRescueEligible: true,
    provider: mockProviders[3],
    distance: 3.1,
    distanceKm: 3.1,
    recommendationScore: 0.91,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fl-4',
    providerId: 'prov-2',
    provider_id: 'prov-2',
    title: 'Chettinad Chicken Masala & Parotta Combo',
    food_name: 'Chettinad Chicken Masala & Parotta Combo',
    category: FoodCategory.MEALS,
    description: 'Stone-ground Chettinad pepper chicken curry served with 3 flaky Malabar parottas. Packed securely in leakproof meal containers.',
    quantity: 6,
    remaining_quantity: 6,
    unit: 'combos',
    originalPrice: 290,
    original_price: 290,
    discountedPrice: 130,
    surplus_price: 130,
    prepared_at: getPreparedAt(3.5),
    collection_deadline: getDeadline(1.5),
    expiresAt: getDeadline(1.5),
    location: 'T. Nagar, Chennai',
    latitude: 13.0418,
    longitude: 80.2341,
    image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800',
    images: ['https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800'],
    dietaryTags: ['Non-Veg', 'Halal'],
    dietary_info: ['Non-Veg', 'Halal'],
    status: FoodStatus.ACTIVE,
    urgencyLevel: UrgencyLevel.URGENT,
    urgency_level: UrgencyLevel.URGENT,
    urgencyScore: 0.94,
    isRescueEligible: true,
    provider: mockProviders[1],
    distance: 1.8,
    distanceKm: 1.8,
    recommendationScore: 0.93,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fl-5',
    providerId: 'prov-3',
    provider_id: 'prov-3',
    title: 'Multi-Grain Sourdough Bread Loaves',
    food_name: 'Multi-Grain Sourdough Bread Loaves',
    category: FoodCategory.BAKERY,
    description: 'Slow-fermented 36-hour sourdough loaves packed with sunflower seeds, flax, and sesame. Perfect for artisanal toast and sandwiches.',
    quantity: 10,
    remaining_quantity: 10,
    unit: 'loaves',
    originalPrice: 160,
    original_price: 160,
    discountedPrice: 60,
    surplus_price: 60,
    prepared_at: getPreparedAt(6),
    collection_deadline: getDeadline(5.0),
    expiresAt: getDeadline(5.0),
    location: 'Adyar, Chennai',
    latitude: 13.0067,
    longitude: 80.2570,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800'],
    dietaryTags: ['Veg', 'Vegan'],
    dietary_info: ['Veg', 'Vegan'],
    status: FoodStatus.ACTIVE,
    urgencyLevel: UrgencyLevel.NORMAL,
    urgency_level: UrgencyLevel.NORMAL,
    urgencyScore: 0.35,
    isRescueEligible: true,
    provider: mockProviders[2],
    distance: 2.4,
    distanceKm: 2.4,
    recommendationScore: 0.79,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fl-6',
    providerId: 'prov-5',
    provider_id: 'prov-5',
    title: 'Farm Fresh Organic Vegetable & Herb Box',
    food_name: 'Farm Fresh Organic Vegetable & Herb Box',
    category: FoodCategory.FRESH_PRODUCE,
    description: 'Assortment of fresh Ooty carrots, English cucumbers, cherry tomatoes, and fresh coriander surplus from morning delivery.',
    quantity: 14,
    remaining_quantity: 14,
    unit: 'crates',
    originalPrice: 200,
    original_price: 200,
    discountedPrice: 75,
    surplus_price: 75,
    prepared_at: getPreparedAt(8),
    collection_deadline: getDeadline(6.0),
    expiresAt: getDeadline(6.0),
    location: 'OMR, Chennai',
    latitude: 12.9348,
    longitude: 80.2312,
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800',
    images: ['https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800'],
    dietaryTags: ['Veg', 'Vegan'],
    dietary_info: ['Veg', 'Vegan'],
    status: FoodStatus.ACTIVE,
    urgencyLevel: UrgencyLevel.NORMAL,
    urgency_level: UrgencyLevel.NORMAL,
    urgencyScore: 0.28,
    isRescueEligible: true,
    provider: mockProviders[4],
    distance: 4.8,
    distanceKm: 4.8,
    recommendationScore: 0.74,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fl-cbe-1',
    providerId: 'prov-cbe-1',
    provider_id: 'prov-cbe-1',
    title: '50 Veg Meals Banquet Surplus',
    food_name: '50 Veg Meals Banquet Surplus',
    category: FoodCategory.MEALS,
    description: 'Fresh authentic Kongu Nadu thali meals prepared for afternoon banquet. Hot sambar, rasam, kootu, poriyal, appalam, and curd. Packed in insulated food-grade containers.',
    quantity: 50,
    remaining_quantity: 50,
    unit: 'meals',
    originalPrice: 120,
    original_price: 120,
    discountedPrice: 50,
    surplus_price: 50,
    prepared_at: getPreparedAt(3),
    collection_deadline: getDeadline(0.9),
    expiresAt: getDeadline(0.9),
    location: 'Gandhipuram, Coimbatore',
    latitude: 11.0168,
    longitude: 76.9558,
    image_url: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800',
    images: ['https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800'],
    dietaryTags: ['Veg', 'Pure Vegetarian'],
    dietary_info: ['Veg', 'Pure Vegetarian'],
    status: FoodStatus.ACTIVE,
    urgencyLevel: UrgencyLevel.URGENT,
    urgency_level: UrgencyLevel.URGENT,
    urgencyScore: 0.95,
    isRescueEligible: true,
    provider: mockProviders[5],
    distance: 0.8,
    distanceKm: 0.8,
    recommendationScore: 0.98,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fl-cbe-2',
    providerId: 'prov-cbe-2',
    provider_id: 'prov-cbe-2',
    title: 'RS Puram Traditional Thali & Tiffin Box',
    food_name: 'RS Puram Traditional Thali & Tiffin Box',
    category: FoodCategory.MEALS,
    description: 'Steaming hot idlis, medu vadai, and mini thali meal with drumstick sambar and coconut chutney.',
    quantity: 20,
    remaining_quantity: 20,
    unit: 'combos',
    originalPrice: 140,
    original_price: 140,
    discountedPrice: 60,
    surplus_price: 60,
    prepared_at: getPreparedAt(2),
    collection_deadline: getDeadline(2.5),
    expiresAt: getDeadline(2.5),
    location: 'RS Puram, Coimbatore',
    latitude: 11.0096,
    longitude: 76.9507,
    image_url: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800',
    images: ['https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800'],
    dietaryTags: ['Veg', 'Pure Vegetarian'],
    dietary_info: ['Veg', 'Pure Vegetarian'],
    status: FoodStatus.ACTIVE,
    urgencyLevel: UrgencyLevel.ATTENTION,
    urgency_level: UrgencyLevel.ATTENTION,
    urgencyScore: 0.68,
    isRescueEligible: true,
    provider: mockProviders[6],
    distance: 1.4,
    distanceKm: 1.4,
    recommendationScore: 0.92,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fl-cbe-3',
    providerId: 'prov-cbe-3',
    provider_id: 'prov-cbe-3',
    title: 'Saibaba Colony Fresh Millet Breads & Biscuits',
    food_name: 'Saibaba Colony Fresh Millet Breads & Biscuits',
    category: FoodCategory.BAKERY,
    description: 'Whole grain ragi and kambu millet cookies with tea cake loaves baked fresh this morning.',
    quantity: 15,
    remaining_quantity: 15,
    unit: 'boxes',
    originalPrice: 180,
    original_price: 180,
    discountedPrice: 70,
    surplus_price: 70,
    prepared_at: getPreparedAt(4),
    collection_deadline: getDeadline(4.5),
    expiresAt: getDeadline(4.5),
    location: 'Saibaba Colony, Coimbatore',
    latitude: 11.0244,
    longitude: 76.9609,
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800'],
    dietaryTags: ['Veg'],
    dietary_info: ['Veg'],
    status: FoodStatus.ACTIVE,
    urgencyLevel: UrgencyLevel.NORMAL,
    urgency_level: UrgencyLevel.NORMAL,
    urgencyScore: 0.32,
    isRescueEligible: true,
    provider: mockProviders[7],
    distance: 2.0,
    distanceKm: 2.0,
    recommendationScore: 0.84,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ============================================================
// ORDERS
// ============================================================
export const mockOrders = [
  {
    id: 'ord-1',
    listingId: 'fl-1',
    listing_id: 'fl-1',
    consumerId: 'cu-1',
    consumer_id: 'cu-1',
    providerId: 'prov-1',
    provider_id: 'prov-1',
    quantity: 2,
    unitPrice: 180,
    unit_price: 180,
    totalPrice: 360,
    total_price: 360,
    status: OrderStatus.READY,
    pickupCode: 'FW-784192',
    pickupPin: '7841',
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    listing: mockFoodListings[0],
    provider: mockProviders[0],
  },
  {
    id: 'ord-2',
    listingId: 'fl-3',
    listing_id: 'fl-3',
    consumerId: 'cu-1',
    consumer_id: 'cu-1',
    providerId: 'prov-4',
    provider_id: 'prov-4',
    quantity: 1,
    unitPrice: 90,
    unit_price: 90,
    totalPrice: 90,
    total_price: 90,
    status: OrderStatus.CONFIRMED,
    pickupCode: 'FW-319402',
    pickupPin: '3194',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    listing: mockFoodListings[2],
    provider: mockProviders[3],
  },
  {
    id: 'ord-3',
    listingId: 'fl-2',
    listing_id: 'fl-2',
    consumerId: 'cu-1',
    consumer_id: 'cu-1',
    providerId: 'prov-3',
    provider_id: 'prov-3',
    quantity: 2,
    unitPrice: 120,
    unit_price: 120,
    totalPrice: 240,
    total_price: 240,
    status: OrderStatus.COMPLETED,
    pickupCode: 'FW-552019',
    pickupPin: '5520',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    listing: mockFoodListings[1],
    provider: mockProviders[2],
  },
];

// ============================================================
// RESCUE REQUESTS
// ============================================================
export const mockRescueRequests = [
  {
    id: 'rr-1',
    listingId: 'fl-1',
    listing_id: 'fl-1',
    providerId: 'prov-1',
    provider_id: 'prov-1',
    quantity: 6,
    triggerReason: 'Commercial collection window expiring in <45 minutes',
    deadline: getDeadline(0.75),
    status: RescueRequestStatus.PENDING,
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    listing: mockFoodListings[0],
    provider: mockProviders[0],
  },
  {
    id: 'rr-2',
    listingId: 'fl-4',
    listing_id: 'fl-4',
    providerId: 'prov-2',
    provider_id: 'prov-2',
    quantity: 4,
    triggerReason: 'Dinner prep transition surplus batch',
    deadline: getDeadline(1.0),
    status: RescueRequestStatus.PENDING,
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    listing: mockFoodListings[3],
    provider: mockProviders[1],
  },
  {
    id: 'rr-3',
    listingId: 'fl-3',
    listing_id: 'fl-3',
    providerId: 'prov-4',
    provider_id: 'prov-4',
    quantity: 8,
    triggerReason: 'Lunch buffet excess donation',
    deadline: getDeadline(1.5),
    status: RescueRequestStatus.CLAIMED,
    rescuePartnerId: 'ngo-1',
    rescue_partner_id: 'ngo-1',
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    listing: mockFoodListings[2],
    provider: mockProviders[3],
    rescuePartner: mockRescuePartners[0],
  },
];

// ============================================================
// INVENTORY
// ============================================================
export const mockInventory = [
  { id: 'inv1', provider_id: 'prov-1', item_name: 'Basmati Rice', category: 'Grains', quantity: 45, unit: 'kg', reorder_level: 10, status: 'NORMAL', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'inv2', provider_id: 'prov-1', item_name: 'Desi Ghee & Oils', category: 'Oils', quantity: 4, unit: 'L', reorder_level: 6, status: 'LOW_STOCK', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'inv3', provider_id: 'prov-1', item_name: 'Fresh Paneer', category: 'Dairy', quantity: 8, unit: 'kg', reorder_level: 5, status: 'NORMAL', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'inv4', provider_id: 'prov-1', item_name: 'Organic Lentils (Toor Dal)', category: 'Pulses', quantity: 2, unit: 'kg', reorder_level: 8, status: 'LOW_STOCK', created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

// ============================================================
// NOTIFICATIONS
// ============================================================
export const mockNotifications = [
  {
    id: 'n1',
    user_id: 'cu-1',
    type: 'ORDER_CONFIRMED',
    title: 'Surplus Reserved Successfully',
    message: 'Your reservation for Biryani Platter is confirmed. Counter pickup ready!',
    reference_id: 'ord-1',
    is_read: false,
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'n2',
    user_id: 'cu-1',
    type: 'URGENT_NEARBY',
    title: '⚡ Urgent Surplus Alert',
    message: 'Taj Coromandel just listed banquet surplus ending in 1h 45m near you.',
    reference_id: 'fl-1',
    is_read: false,
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
];

// ============================================================
// PLATFORM STATS
// ============================================================
export const platformStats = {
  mealsSaved: 12450,
  co2PreventedKg: 31125,
  moneySavedInr: 1867500,
  activeProviders: 47,
  activeRescuePartners: 12,
  totalListings: 48,
  meals_redistributed: 12450,
  food_listings: 48,
  rescue_partners: 12,
  meals_purchased: 9030,
  meals_rescued: 3420,
  completed_orders: 4120,
};

export const mockPlatformStats = platformStats;

// ============================================================
// PROVIDER ANALYTICS
// ============================================================
export const providerAnalytics = {
  totalRevenueRecoveredInr: 84500,
  totalSurplusMealsSold: 420,
  totalDonatedMeals: 110,
  wasteReductionKg: 864,
  co2SavedKg: 2160,
  total_posted: 550,
  total_sold: 420,
  total_rescued: 110,
  total_expired: 20,
  revenue_recovered: 84500,
  recovery_rate: 92.4,
};

// ============================================================
// DAILY ANALYTICS & CATEGORY BREAKDOWN
// ============================================================
export const dailyAnalytics = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  const sold = Math.floor(Math.random() * 18) + 12;
  const donated = Math.floor(Math.random() * 6) + 2;
  return {
    date: date.toISOString().split('T')[0],
    mealsRescued: sold,
    mealsDonated: donated,
    revenueRecoveredInr: sold * 140,
    wasteReductionKg: (sold + donated) * 0.7,
  };
});

export const mockDailyAnalytics = dailyAnalytics;

export const categoryBreakdown = [
  { category: 'Meals & Biryani', percentage: 42, count: 42 },
  { category: 'Bakery & Pastries', percentage: 28, count: 28 },
  { category: 'Fresh Produce', percentage: 16, count: 16 },
  { category: 'Dairy & Beverages', percentage: 14, count: 14 },
];

export const mockCategoryData = categoryBreakdown;

// ============================================================
// DEMO ACCOUNTS
// ============================================================
export const demoUsers = {
  consumer: {
    email: 'consumer@foodwise.demo',
    password: 'Demo@1234',
    name: 'Priya Sharma',
    role: UserRole.CONSUMER,
  },
  provider: {
    email: 'provider@foodwise.demo',
    password: 'Demo@1234',
    name: 'Chef Rajesh Kumar (Taj Coromandel)',
    role: UserRole.PROVIDER,
  },
  rescue: {
    email: 'rescue@foodwise.demo',
    password: 'Demo@1234',
    name: 'Sunita Rao (Robin Hood Army)',
    role: UserRole.RESCUE_PARTNER,
  },
  admin: {
    email: 'admin@foodwise.demo',
    password: 'Demo@1234',
    name: 'Dr. Aris Thorne (System Admin)',
    role: UserRole.ADMIN,
  },
};
